version: "3.9"

services:
  ats-staging-be:
    build:
      context: .
    image: ats-staging-be
    container_name: ats-staging-be
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - ats-network

  ats-demo-be:
    build:
      context: .
    image: ats-demo-be
    container_name: ats-demo-be
    restart: always
    ports:
      - 8001:8000
    env_file:
      - .env
    networks:
      - ats-network

networks:
  ats-network:
    external: true
